-- DROPPING THE TABLE IF EXISTS ALREADY
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS EMPLOYEE;   

--  CREATING THE TABLE WITH PARENT AND CHILD RELATIONSHIP
-- EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (  
id bigint  AUTO_INCREMENT  PRIMARY KEY,  
first_name VARCHAR(255) NOT NULL,  
last_name VARCHAR(255) NOT NULL, 
dateOfBirth DATE 
);

-- ADDRESS TABLE
CREATE TABLE ADDRESS (  
id bigint  AUTO_INCREMENT  PRIMARY KEY,  
emp_id bigint  NOT NULL,
line1 VARCHAR(255) NOT NULL,  
line2 VARCHAR(255) DEFAULT NULL, 
city VARCHAR(100) DEFAULT NULL, 
state VARCHAR(50) DEFAULT NULL, 
country VARCHAR(50) ,
zip_code VARCHAR(6)
);

 ALTER TABLE ADDRESS ADD FOREIGN KEY (emp_id) REFERENCES EMPLOYEE(id);